#!/usr/bin/env bash

cdplus(){
  QUIET=0
  EXEC_AFTER="ls"
  DIR=$HOME

  until [ -z "$1" ]; do
  PARAM="$1"
    if [ "$PARAM" == "-q" ]||[ "$PARAM" == "--quiet" ]; then
      QUIET=1
    elif [ "$PARAM" == "-e" ]||[ "$PARAM" == "--exec" ]; then
      shift
      EXEC_AFTER="$1"
    else
      DIR="$PARAM"
    fi
    shift 1
  done

  # here's the hack! ugh, right? all this to change
  # directories!
  pushd "$DIR" > /dev/null 2> $HOME/.cdplus.err
  # as far as I can tell, this is only necessary on OSX, and only
  # to keep your dstack clean...
  popd > /dev/null 2>&1
  if [ $? -ne 0 ]; then
    QUIET=1
    sed -e "s/^.*pushd:/$0:/" $HOME/.cdplus.err
  fi
  if [ $QUIET -ne 1 ]; then
    $EXEC_AFTER
  fi
}

if [[ $0 != *bash ]]; then
  echo 
  echo "You're doing it wrong!"
  echo
  echo "Try this:"
  echo "$PWD# source $0"
  echo "$PWD# alias cd=\"cdplus\""
  echo "$PWD# cd ~"
  echo
fi 
